export const tags = [
  "Farms",
  "Amazing Views",
  "Treehouses",
  "Rooms",
  "Design",
  "Amazing Pools",
  "OMG",
  "BeachFront",
  "Tiny Homes",
  "LakeFront",
  "Trending",
  "Off-the-Grid",
  "Historical Homes",
  "Castles",
  "National Parks",
  "Luxe",
  "Lake",
  "Mansions",
  "Tropical",
  "Bed and Breakfast",
  "Countryside",
  "Top Cities",
  "Top of the World",
  "Caves",
  "Shepherd's Huts",
  "A-Frames",
  "Camping",
  "Play",
  "Boats",
  "Deserts",
  "Houseboats",
  "Beach",
];
